### PR TITLE
Consolidate all app data and provide backend interface to allow creation, deletion and name validation of generators

### LINKED ISSUE #119: Normalize QSharedPointer access style
Right now, access to properties of objects pointed to by QSharedPointers is very messy; it is a mixture of

`sharedPointer.get()->member`
`sharedPointer.data()->member`
`sharedPointer->member`

We should stick to the latter.

### LINKED ISSUE #155: Create a new generator backend
See #39 

Create and connect the new generator with its 
- facade 
- OSC sender/receiver
- compute engine

### LINKED ISSUE #157: Delete a generator on the backend
See #40

Delete the generator's
- facade
- OSC sender/receiver

### LINKED ISSUE #160: Invistigate a structure to represent the different parts of the generators
Trouver une structure pour representer 
- les connections entre les différentes parties du générateurs (façade, OSC...)
- les connections entre générateurs

Propositions: command pattern
https://wiki.c2.com/?DecoratorPattern https://en.wikipedia.org/wiki/Database-centric_architecture
https://wiki.c2.com/?CommandPattern

### PR DESCRIPTION
**Pull request by simondemeule**
This refactors code spread out through the main, `OscEngine`, `ComputeEngine`, and `Generator` into the `AppModel` singleton class, which stores all of the app's data, manages threads, and manages all connection creation and destruction when generators are added or removed.

This closes #160, closes #155, closes #157, closes #119, and provides functions necessary to implement #136 (to prevent having multiple generators with the same name, which would break automatic OSC address naming) and #75 (provides a way for QML created QQuickObjects to access generator data through the static `AppModel` singleton).

`AppModel` is exposed to QMl as `appModel`, and has the following `Q_INVOKABLE` methods:

- `Q_INVOKABLE void createGenerator();` for creating a generator
- `Q_INVOKABLE void deleteGenerator(int id);` for deleting a generator using the generator's id
- `Q_INVOKABLE bool validateNewGeneratorName(QString name);` for validating that a chosen generator name is not already in use

### CODE REVIEW

**Comment by lucidism** [comment]
@simondemeule I'm not 100% sure if that's what at cause here, but I think the model isn't fully updated when a generator is created/deleted.

I ran this test in which a generator is created as soon as the window component (in QML) is initialized:
```
Component.onCompleted: appModel.createGenerator()
Timer {
    running: true; repeat: false; interval: 3000
    onTriggered: appModel.deleteGenerator(0)
}
```
however, the GUI isn't affected in any way, I can still interact with every property field, and the SNN is running regardless since the history graph seems to be active. and yet, `ComputeEngine::deleteGenerator` is fully executed, which I've confirmed with a `qDebug` call right before the `return` clause. am I missing something? 🤔

**Comment by lucidism** [comment]
also, line 61 in `main.cpp` is unnecessary:
```
qmlRegisterUncreatableType<AppModel>("ca.hexagram.xmodal.autonomx", 1, 0, "AppModel", "Cannot instanciate AppModel.");
```
`appModel` is already contextualized through `rootContext()->setContextProperty`, in the same way that `generatorModel` is and all of its attached `Generator` and `GeneratorFacade` objects aren't.

**Comment by simondemeule** [comment]
@lucidism thanks for catching that. I think `GeneratorModel` is lacking some `dataChanged` signals when generators are added or removed.

**Comment by simondemeule** [comment]
@lucidism fixed! Turns out I wasn't calling some of `QAbstractListModel`'s methods that deal with insertion and removal of elements from the list. I've also removed the redundant type declaration.

**Pull request merged**
