### PR TITLE
Documentation on the Architecture

### LINKED ISSUE #259: Document the current generator architecture and the changes we want to do on it
Document the current generator architecture and the changes we want to do on it.

## Criteria
- Asks questions to @simondemeule about the current architecture and how we could change.
- Document the current architecture and the way we could refactor in the doc/architecture.md text file.
- Document how we could implement a game of life (GOL) and the Wolfram automata with the current architecture

## Technical details
- Perhaps add the markdown architecture documentation files to the Doxygen build, so that they're included in the HTML output. (it's also possible to add images to that)

### PR DESCRIPTION
**Pull request by puneet798**
Part of #259

### CODE REVIEW

**Review by jvlyndark — DISMISSED** [review]

**Review by aalex — CHANGES_REQUESTED** [review]
I think that you could/should:
- Create a "doc" folder and move this file to it?
- In the CONTRIBUTING.md file, mention this file under a level 2 title. "## Notes about the software architecture"
- In this file, add a level 1 title "# Notes about the software archicture"

**Review by jvlyndark — APPROVED** [review]
LGTM!

**Comment by jvlyndark** [comment]
@aalex i think your review is needed in order to close this PR. Julien made the changes requested and I've reviewed them but merging is blocked by requested changes.

**Review by aalex — APPROVED** [review]
LGTM

**Comment by aalex** [comment]
Can you squash and merge it @puneet798 ?

**Pull request merged**
